plugins {
    id 'application'
}

ext {
    fabric8Version = '6.13.4'
    kafkaVersion = '3.7.0'
}

application {
    mainClass = 'com.streamflow.controlplane.api.ActivationApiApp'
}

dependencies {
    implementation project(':common')
    implementation "org.apache.kafka:kafka-streams:${kafkaVersion}"
    implementation "io.fabric8:kubernetes-client:${fabric8Version}"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "io.fabric8:kubernetes-server-mock:${fabric8Version}"
}

tasks.register('ActivationApi', JavaExec) {
    group = 'application'
    description = "Runs ${'com.streamflow.controlplane.api.ActivationApiApp'}"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.streamflow.controlplane.api.ActivationApiApp'
}
